### ISSUE TITLE
Non-Excel files are corrupt

### ISSUE THREAD

**Issue by skhiggins** [skhiggins/PythonTools#6]
The only scraped files that I can open are the Excels, the rest (e.g. pdf, zip) are corrupt files. (Try opening them after scraping and see if the same happens for you.) You might have to modify the code depending on the file type because the original code I wrote was with Excel files in mind.

**Comment by angelynaye** [comment]
Fixed the way to open the .zip files(It can read in the .zip files right now ), but still cannot open the .zip files online, because the hidden link to .zip files is said to be a link leads to files type other than .zip type file. (Have tried to navigate to the specific url which contains the .zip files link, and click the link inside the href (using inspect). However, same with the web scraping result, no .zip files is able to be downloaded by the direct click). Still looking for reasons

**Comment by skhiggins** [comment]
It looks like the zip issue was indeed solved in pull request #31, but now the pdf files downloaded in  [`test_get_files_zip_files.ipynb`](https://github.com/skhiggins/PythonTools/blob/master/tests/test_get_files_zip_files.ipynb) won't open. Could you look into this @angelynaye?

**Comment by angelynaye** [comment]
Solved in #35
